### ISSUE TITLE
About ransformers-4.46.2

### ISSUE THREAD

**Issue by Kirovsiki** [IDEA-Research/MotionCLR#2]
Hi,it is very happy to see that you have shared your work, we noticed while configuring the environment that there are configuration conflicts here and perhaps need to work around them:
Using cached transformers-4.46.2-py3-none-any.whl.metadata (44 kB)
ERROR: Exception:
Traceback (most recent call last):
  File "/home/kud/miniconda3/envs/motionclr2/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 105, in _run_wrapper
    status = _inner_run()
  File "/home/kud/miniconda3/envs/motionclr2/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 96, in _inner_run
    return self.run(options, args)
  File "/home/kud/miniconda3/envs/motionclr2/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 67, in wrapper
    return func(self, options, args)
  File "/home/kud/miniconda3/envs/motionclr2/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 379, in run
    requirement_set = resolver.resolve(
  File "/home/kud/miniconda3/envs/motionclr2/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
  File "/home/kud/miniconda3/envs/motionclr2/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/kud/miniconda3/envs/motionclr2/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 457, in resolve
    raise ResolutionTooDeep(max_rounds)
pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 200000

**Comment by Kirovsiki** [comment]
I'm sorry to say that we have discovered that the model will not correspond to the weight size if the test is executed in the same way. Is this not set correctly? These are reporting errors:Traceback (most recent call last):
  File "/home/kud/miniconda3/envs/motionclr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/kud/miniconda3/envs/motionclr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/kud/main/MotionCLR2/MotionCLR/scripts/evaluation.py", line 44, in <module>
    eval_wrapper = EvaluatorModelWrapper(opt)
  File "/home/kud/main/MotionCLR2/MotionCLR/eval/evaluator_wrapper.py", line 63, in __init__
    self.text_encoder, self.motion_encoder, self.movement_encoder = build_models(opt)
  File "/home/kud/main/MotionCLR2/MotionCLR/eval/evaluator_wrapper.py", line 23, in build_models
    movement_enc.load_state_dict(checkpoint['movement_encoder'],strict=False)
  File "/home/kud/miniconda3/envs/motionclr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2153, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for MovementConvEncoder:
	size mismatch for main.0.weight: copying a param with shape torch.Size([512, 247, 4]) from checkpoint, the shape in current model is torch.Size([512, 259, 4]).

**Comment by LinghaoChan** [comment]
@Kirovsiki Sorry for the late reply. I found the GitHub messages are missed recently. I seems that the error you met is about the evaluator. Right?

**Comment by Kirovsiki** [comment]
This would include when starting with app.py. I tried to retrain the model and it loaded successfully, and it can work fine for now.

> @Kirovsiki Sorry for the late reply. I found the GitHub messages are missed recently. I seems that the error you met is about the evaluator. Right?

This would include when starting with app.py. I tried to retrain the model and it loaded successfully, and it can work fine for now.

**Comment by LinghaoChan** [comment]
> This would include when starting with app.py. I tried to retrain the model and it loaded successfully, and it can work fine for now.
> 
> > @Kirovsiki Sorry for the late reply. I found the GitHub messages are missed recently. I seems that the error you met is about the evaluator. Right?
> 
> This would include when starting with app.py. I tried to retrain the model and it loaded successfully, and it can work fine for now.

Congrats to resolve that. If you could provide more info about the error, it will be beneficial to the community.
